taozihao ~/desktop/Project-Happy-4/Happy_4$nosetests
.. 0.01 %  @ 0
 2.01 %  @ 175
 4.01 %  @ 350
 6.00 %  @ 525
 8.00 %  @ 700
10.00 %  @ 875
12.00 %  @ 1050
14.00 %  @ 1225
15.99 %  @ 1400
17.99 %  @ 1575
19.99 %  @ 1750
21.99 %  @ 1925
23.98 %  @ 2100
25.98 %  @ 2275
27.98 %  @ 2450
29.98 %  @ 2625
31.97 %  @ 2800
33.97 %  @ 2975
35.97 %  @ 3150
37.97 %  @ 3325
39.97 %  @ 3500
41.96 %  @ 3675
43.96 %  @ 3850
45.96 %  @ 4025
47.96 %  @ 4200
49.95 %  @ 4375
51.95 %  @ 4550
53.95 %  @ 4725
55.95 %  @ 4900
57.95 %  @ 5075
59.94 %  @ 5250
61.94 %  @ 5425
63.94 %  @ 5600
65.94 %  @ 5775
67.93 %  @ 5950
69.93 %  @ 6125
71.93 %  @ 6300
73.93 %  @ 6475
75.92 %  @ 6650
77.92 %  @ 6825
79.92 %  @ 7000
81.92 %  @ 7175
83.92 %  @ 7350
85.91 %  @ 7525
87.91 %  @ 7700
89.91 %  @ 7875
91.91 %  @ 8050
93.90 %  @ 8225
95.90 %  @ 8400
97.90 %  @ 8575
99.90 %  @ 8750
. 0.01 %  @ 0
 2.01 %  @ 175
 4.01 %  @ 350
 6.00 %  @ 525
 8.00 %  @ 700
10.00 %  @ 875
12.00 %  @ 1050
14.00 %  @ 1225
15.99 %  @ 1400
17.99 %  @ 1575
19.99 %  @ 1750
21.99 %  @ 1925
23.98 %  @ 2100
25.98 %  @ 2275
27.98 %  @ 2450
29.98 %  @ 2625
31.97 %  @ 2800
33.97 %  @ 2975
35.97 %  @ 3150
37.97 %  @ 3325
39.97 %  @ 3500
41.96 %  @ 3675
43.96 %  @ 3850
45.96 %  @ 4025
47.96 %  @ 4200
49.95 %  @ 4375
51.95 %  @ 4550
53.95 %  @ 4725
55.95 %  @ 4900
57.95 %  @ 5075
59.94 %  @ 5250
61.94 %  @ 5425
63.94 %  @ 5600
65.94 %  @ 5775
67.93 %  @ 5950
69.93 %  @ 6125
71.93 %  @ 6300
73.93 %  @ 6475
75.92 %  @ 6650
77.92 %  @ 6825
79.92 %  @ 7000
81.92 %  @ 7175
83.92 %  @ 7350
85.91 %  @ 7525
87.91 %  @ 7700
89.91 %  @ 7875
91.91 %  @ 8050
93.90 %  @ 8225
95.90 %  @ 8400
97.90 %  @ 8575
99.90 %  @ 8750
...F.
======================================================================
FAIL: test_wind_input.test_wind_value_output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/taozihao/miniconda3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/taozihao/Desktop/Project-Happy-4/Happy_4/test_wind_input.py", line 29, in test_wind_value_output
    assert a.iloc[0]['generation']==12.914752,'cannot get right daily wind value'
AssertionError: cannot get right daily wind value
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): developer.nrel.gov
urllib3.connectionpool: DEBUG: http://developer.nrel.gov:80 "GET /api/wind/srw_aggregate_extract?api_key=CNN87trTlIjPrPURSZM9VEUDnWzKulgUFtUVjUmr&year=2010&lat=30&lon=-100 HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 8 tests in 65.169s

FAILED (failures=1)
